
version: '3.8'
services:
  app:
    build: ./app
    container_name: student_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    restart: unless-stopped
    networks:
      - devops_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - devops_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - devops_net
    depends_on:
      - prometheus

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - devops_net

  jmeter:
    image: justb4/jmeter:5.5
    container_name: jmeter
    networks:
      - devops_net
    entrypoint: ["/bin/sh","-c","echo 'JMeter container ready (configure test plan in /tests/jmeter)'; sleep infinity"]

volumes:
  jenkins_home:

networks:
  devops_net:
    driver: bridge
