
services:
  api:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - jenkins
      - grafana

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - '8080:8080'
    volumes:
      - jenkins_home:/var/jenkins_home

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  jenkins_home: